server:
  port: 10002
spring:
  application:
    name: config-ssm
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/bmcar?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.joey.demo.pojo
  mapper-locations: classpath:mapping/*.xml
